package com.inolia_zaicek.mine_fargo.Config;

import net.minecraftforge.common.ForgeConfigSpec;

public class MyGoConfig {
    public static final ForgeConfigSpec.Builder BUILDER = new ForgeConfigSpec.Builder();
    public static final ForgeConfigSpec SPEC;

    public static final ForgeConfigSpec.DoubleValue iron_soul_stone;
    public static final ForgeConfigSpec.DoubleValue gold_soul_stone;
    public static final ForgeConfigSpec.DoubleValue diamond_soul_stone_looting;
    public static final ForgeConfigSpec.DoubleValue diamond_soul_stone_fortune;
    public static final ForgeConfigSpec.DoubleValue lapis_lazuli_soul_stone;
    public static final ForgeConfigSpec.DoubleValue redstone_soul_stone;
    public static final ForgeConfigSpec.DoubleValue emerald_soul_stone;
    public static final ForgeConfigSpec.DoubleValue copper_soul_stone;
    public static final ForgeConfigSpec.DoubleValue coal_soul_stone;
    public static final ForgeConfigSpec.DoubleValue netherite_soul_stone;
    public static final ForgeConfigSpec.DoubleValue netherite_soul_stone_armor;
    public static final ForgeConfigSpec.DoubleValue nether_soul_stone;
    public static final ForgeConfigSpec.DoubleValue mushroom_soul_stone;
    public static final ForgeConfigSpec.DoubleValue ender_soul_stone_attack;
    public static final ForgeConfigSpec.DoubleValue ender_soul_stone_armor;
    public static final ForgeConfigSpec.DoubleValue ocean_soul_stone;
    public static final ForgeConfigSpec.DoubleValue lush_soul_stone_food;
    public static final ForgeConfigSpec.DoubleValue lush_soul_stone_saturation;
    public static final ForgeConfigSpec.DoubleValue forest_soul_stone;
    public static final ForgeConfigSpec.DoubleValue blaze_soul_stone;
    public static final ForgeConfigSpec.DoubleValue death_soul_stone;
    public static final ForgeConfigSpec.DoubleValue arthropod_soul_stone;
    public static final ForgeConfigSpec.DoubleValue animal_soul_stone;
    public static final ForgeConfigSpec.DoubleValue aquatic_soul_stone;
    public static final ForgeConfigSpec.DoubleValue wing_soul_stone;
    public static final ForgeConfigSpec.DoubleValue fire_sect_soul_stone_fire_power;
    public static final ForgeConfigSpec.DoubleValue fire_sect_soul_stone_fire_max_damage;
    public static final ForgeConfigSpec.DoubleValue fire_sect_soul_stone_fire_min_damage;
    public static final ForgeConfigSpec.DoubleValue ice_sect_soul_stone_ice_power;
    public static final ForgeConfigSpec.DoubleValue ice_sect_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue ice_sect_soul_stone_ice_damage;
    public static final ForgeConfigSpec.DoubleValue lightning_sect_soul_stone_power;
    public static final ForgeConfigSpec.DoubleValue lightning_sect_soul_stone_damage;
    public static final ForgeConfigSpec.DoubleValue lightning_sect_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue holy_sect_soul_stone_power;
    public static final ForgeConfigSpec.DoubleValue holy_sect_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue holy_sect_soul_stone_damage;
    public static final ForgeConfigSpec.DoubleValue evocation_sect_soul_stone_power;
    public static final ForgeConfigSpec.DoubleValue evocation_sect_soul_stone_damage;
    public static final ForgeConfigSpec.DoubleValue evocation_sect_soul_stone_armor;
    public static final ForgeConfigSpec.DoubleValue nature_sect_soul_stone_power;
    public static final ForgeConfigSpec.DoubleValue nature_sect_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue nature_sect_soul_stone_chance;
    public static final ForgeConfigSpec.DoubleValue nature_sect_soul_stone_level;
    public static final ForgeConfigSpec.DoubleValue blood_sect_soul_stone_power;
    public static final ForgeConfigSpec.DoubleValue blood_sect_soul_stone_heal;
    public static final ForgeConfigSpec.DoubleValue blood_sect_soul_stone_owner;
    public static final ForgeConfigSpec.DoubleValue ender_sect_soul_stone_power;
    public static final ForgeConfigSpec.DoubleValue ender_sect_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue ender_sect_soul_stone_damage;
    public static final ForgeConfigSpec.DoubleValue eldritch_sect_soul_stone_power;
    public static final ForgeConfigSpec.DoubleValue eldritch_sect_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue eldritch_sect_soul_stone_damage;
    static {
        //祝福
        BUILDER.push("base");
        eldritch_sect_soul_stone_damage = BUILDER.comment("邪术学派魂石伤害增幅").defineInRange("eldritch_sect_soul_stone_damage",0.075,0F,2147483647);
        eldritch_sect_soul_stone_time = BUILDER.comment("邪术学派魂石抑影时间").defineInRange("eldritch_sect_soul_stone_time",10,0F,2147483647);
        eldritch_sect_soul_stone_power = BUILDER.comment("邪术学派魂石法强").defineInRange("eldritch_sect_soul_stone_power",0.1,0F,2147483647);
        ender_sect_soul_stone_damage = BUILDER.comment("末影学派魂石伤害增幅").defineInRange("ender_sect_soul_stone_damage",0.1,0F,2147483647);
        ender_sect_soul_stone_time = BUILDER.comment("末影学派魂石抑影时间").defineInRange("ender_sect_soul_stone_time",10,0F,2147483647);
        ender_sect_soul_stone_power = BUILDER.comment("末影学派魂石法强").defineInRange("ender_sect_soul_stone_power",0.1,0F,2147483647);
        blood_sect_soul_stone_owner = BUILDER.comment("血腥学派魂石宠物吸血转化").defineInRange("blood_sect_soul_stone_owner",0.5,0F,2147483647);
        blood_sect_soul_stone_heal = BUILDER.comment("血腥学派魂石自身吸血").defineInRange("blood_sect_soul_stone_heal",0.15,0F,2147483647);
        blood_sect_soul_stone_power = BUILDER.comment("血腥学派魂石法强").defineInRange("blood_sect_soul_stone_power",0.1,0F,2147483647);
        nature_sect_soul_stone_power = BUILDER.comment("自然学派魂石法强").defineInRange("nature_sect_soul_stone_power",0.1,0F,2147483647);
        nature_sect_soul_stone_time = BUILDER.comment("自然学派魂石buff增加时间").defineInRange("nature_sect_soul_stone_time",0.2,0F,2147483647);
        nature_sect_soul_stone_chance = BUILDER.comment("自然学派魂石buff提升概率").defineInRange("nature_sect_soul_stone_chance",0.3,0F,2147483647);
        nature_sect_soul_stone_level = BUILDER.comment("自然学派魂石最高buff提升等级").defineInRange("nature_sect_soul_stone_level",15,0F,2147483647);
        evocation_sect_soul_stone_armor = BUILDER.comment("唤魔学派魂石随从减伤").defineInRange("evocation_sect_soul_stone_armor",0.3,0F,2147483647);
        evocation_sect_soul_stone_damage = BUILDER.comment("唤魔学派魂石随从增伤").defineInRange("evocation_sect_soul_stone_damage",0.15,0F,2147483647);
        evocation_sect_soul_stone_power = BUILDER.comment("唤魔学派魂石法强").defineInRange("evocation_sect_soul_stone_power",0.1,0F,2147483647);
        holy_sect_soul_stone_time = BUILDER.comment("神圣学派魂石时长").defineInRange("holy_sect_soul_stone_time",10,0F,2147483647);
        holy_sect_soul_stone_damage = BUILDER.comment("神圣学派魂石伤害增幅").defineInRange("holy_sect_soul_stone_damage",0.1,0F,2147483647);
        holy_sect_soul_stone_power = BUILDER.comment("神圣学派魂石法强").defineInRange("holy_sect_soul_stone_power",0.1,0F,2147483647);
        lightning_sect_soul_stone_time = BUILDER.comment("雷霆学派魂石最长超负荷时长").defineInRange("lightning_sect_soul_stone_time",10,0F,2147483647);
        lightning_sect_soul_stone_damage = BUILDER.comment("雷霆学派魂石伤害转化比例").defineInRange("lightning_sect_soul_stone_damage",0.2,0F,2147483647);
        lightning_sect_soul_stone_power = BUILDER.comment("雷霆学派魂石雷霆法强").defineInRange("lightning_sect_soul_stone_power",0.1,0F,2147483647);
        ice_sect_soul_stone_ice_power = BUILDER.comment("冰霜学派魂石冰霜法强").defineInRange("ice_sect_soul_stone_ice_power",0.1,0F,2147483647);
        ice_sect_soul_stone_time = BUILDER.comment("冰霜学派魂石冰封时间").defineInRange("ice_sect_soul_stone_time",10,0F,2147483647);
        ice_sect_soul_stone_ice_damage = BUILDER.comment("冰霜学派魂石冰封增伤").defineInRange("ice_sect_soul_stone_ice_damage",0.1,0F,2147483647);
        fire_sect_soul_stone_fire_max_damage = BUILDER.comment("炽焰学派魂石炽焰最大增幅").defineInRange("fire_sect_soul_stone_fire_max_damage",0.15,0F,2147483647);
        fire_sect_soul_stone_fire_min_damage = BUILDER.comment("炽焰学派魂石炽焰最小增幅").defineInRange("fire_sect_soul_stone_fire_min_damage",0.05,0F,2147483647);
        fire_sect_soul_stone_fire_power = BUILDER.comment("炽焰学派魂石炽焰法强").defineInRange("fire_sect_soul_stone_fire_power",0.1,0F,2147483647);
        wing_soul_stone = BUILDER.comment("飞翼魂石飞行速度").defineInRange("wing_soul_stone",1,0F,2147483647);
        aquatic_soul_stone = BUILDER.comment("水生魂石水下增伤").defineInRange("aquatic_soul_stone",0.15,0F,2147483647);
        animal_soul_stone = BUILDER.comment("动物魂石额外战利品数量").defineInRange("animal_soul_stone",1,0F,2147483647);
        arthropod_soul_stone = BUILDER.comment("节肢增伤").defineInRange("arthropod_soul_stone",0.15,0F,2147483647);
        death_soul_stone = BUILDER.comment("亡灵增伤").defineInRange("death_soul_stone",0.15,0F,2147483647);
        blaze_soul_stone = BUILDER.comment("狱灵增伤").defineInRange("blaze_soul_stone",0.15,0F,2147483647);
        forest_soul_stone = BUILDER.comment("森林间隔").defineInRange("forest_soul_stone",3,0F,2147483647);
        lush_soul_stone_saturation = BUILDER.comment("自然饱和度").defineInRange("lush_soul_stone_saturation",1,0F,2147483647);
        lush_soul_stone_food = BUILDER.comment("自然饥饿度").defineInRange("lush_soul_stone_food",1,0F,2147483647);
        ocean_soul_stone = BUILDER.comment("海洋游泳速度").defineInRange("ocean_soul_stone",0.50,0F,2147483647);
        ender_soul_stone_attack = BUILDER.comment("末地-末影人特攻").defineInRange("ender_soul_stone_attack",0.5,0F,2147483647);
        ender_soul_stone_armor = BUILDER.comment("末地-末影人特防").defineInRange("ender_soul_stone_armor",0.4,0F,2147483647);
        mushroom_soul_stone = BUILDER.comment("蘑菇魂石概率").defineInRange("mushroom_soul_stone",0.5,0F,2147483647);
        nether_soul_stone = BUILDER.comment("下界魂石增伤").defineInRange("nether_soul_stone",0.15,0F,2147483647);
        netherite_soul_stone = BUILDER.comment("下界合金魂石击退抗性").defineInRange("netherite_soul_stone",0.4,0F,2147483647);
        netherite_soul_stone_armor = BUILDER.comment("下界合金魂石护甲韧性").defineInRange("netherite_soul_stone_armor",3,0F,2147483647);
        coal_soul_stone = BUILDER.comment("煤炭魂石移速").defineInRange("coal_soul_stone",0.2,0F,2147483647);
        copper_soul_stone = BUILDER.comment("铜魂石挖掘速度").defineInRange("copper_soul_stone",0.5,0F,2147483647);
        emerald_soul_stone = BUILDER.comment("绿宝石魂石声望").defineInRange("emerald_soul_stone",100,0F,2147483647);
        redstone_soul_stone = BUILDER.comment("红石攻击速度").defineInRange("redstone_soul_stone",0.25,0F,2147483647);
        iron_soul_stone = BUILDER.comment("铁魂石护甲值").defineInRange("iron_soul_stone",5,0F,2147483647);
        gold_soul_stone = BUILDER.comment("金魂石附魔等级").defineInRange("gold_soul_stone",5,0F,2147483647);
        diamond_soul_stone_looting = BUILDER.comment("钻石魂石抢夺").defineInRange("diamond_soul_stone_looting",2,0F,100);
        diamond_soul_stone_fortune = BUILDER.comment("钻石魂石时运").defineInRange("diamond_soul_stone_fortune",2,0F,100);
        lapis_lazuli_soul_stone = BUILDER.comment("青金石经验倍率").defineInRange("lapis_lazuli_soul_stone",1,0F,100);
        BUILDER.pop();
        SPEC = BUILDER.build();
    }
}
