package com.inolia_zaicek.mine_fargo.Config;

import net.minecraftforge.common.ForgeConfigSpec;

public class MyGoConfig {
    public static final ForgeConfigSpec.Builder BUILDER = new ForgeConfigSpec.Builder();
    public static final ForgeConfigSpec SPEC;

    public static final ForgeConfigSpec.DoubleValue iron_soul_stone;
    public static final ForgeConfigSpec.DoubleValue gold_soul_stone;
    public static final ForgeConfigSpec.DoubleValue diamond_soul_stone_looting;
    public static final ForgeConfigSpec.DoubleValue diamond_soul_stone_fortune;
    public static final ForgeConfigSpec.DoubleValue lapis_lazuli_soul_stone;
    public static final ForgeConfigSpec.DoubleValue redstone_soul_stone;
    public static final ForgeConfigSpec.DoubleValue emerald_soul_stone;
    public static final ForgeConfigSpec.DoubleValue copper_soul_stone;
    public static final ForgeConfigSpec.DoubleValue coal_soul_stone;
    public static final ForgeConfigSpec.DoubleValue netherite_soul_stone;
    public static final ForgeConfigSpec.DoubleValue netherite_soul_stone_armor;
    public static final ForgeConfigSpec.DoubleValue nether_soul_stone;
    public static final ForgeConfigSpec.DoubleValue mushroom_soul_stone;
    public static final ForgeConfigSpec.DoubleValue ender_soul_stone_attack;
    public static final ForgeConfigSpec.DoubleValue ender_soul_stone_armor;
    public static final ForgeConfigSpec.DoubleValue ocean_soul_stone;
    public static final ForgeConfigSpec.DoubleValue lush_soul_stone_food;
    public static final ForgeConfigSpec.DoubleValue lush_soul_stone_saturation;
    public static final ForgeConfigSpec.DoubleValue forest_soul_stone;
    public static final ForgeConfigSpec.DoubleValue blaze_soul_stone;
    public static final ForgeConfigSpec.DoubleValue death_soul_stone;
    public static final ForgeConfigSpec.DoubleValue arthropod_soul_stone;
    public static final ForgeConfigSpec.DoubleValue animal_soul_stone;
    public static final ForgeConfigSpec.DoubleValue aquatic_soul_stone;
    public static final ForgeConfigSpec.DoubleValue wing_soul_stone;
    public static final ForgeConfigSpec.DoubleValue fire_sect_soul_stone_fire_power;
    public static final ForgeConfigSpec.DoubleValue fire_sect_soul_stone_fire_max_damage;
    public static final ForgeConfigSpec.DoubleValue fire_sect_soul_stone_fire_min_damage;
    public static final ForgeConfigSpec.DoubleValue ice_sect_soul_stone_ice_power;
    public static final ForgeConfigSpec.DoubleValue ice_sect_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue ice_sect_soul_stone_ice_damage;
    public static final ForgeConfigSpec.DoubleValue lightning_sect_soul_stone_power;
    public static final ForgeConfigSpec.DoubleValue lightning_sect_soul_stone_damage;
    public static final ForgeConfigSpec.DoubleValue lightning_sect_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue holy_sect_soul_stone_power;
    public static final ForgeConfigSpec.DoubleValue holy_sect_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue holy_sect_soul_stone_damage;
    public static final ForgeConfigSpec.DoubleValue evocation_sect_soul_stone_power;
    public static final ForgeConfigSpec.DoubleValue evocation_sect_soul_stone_owner_damage;
    public static final ForgeConfigSpec.DoubleValue evocation_sect_soul_stone_damage;
    public static final ForgeConfigSpec.DoubleValue evocation_sect_soul_stone_armor;
    public static final ForgeConfigSpec.DoubleValue nature_sect_soul_stone_power;
    public static final ForgeConfigSpec.DoubleValue nature_sect_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue nature_sect_soul_stone_chance;
    public static final ForgeConfigSpec.DoubleValue nature_sect_soul_stone_level;
    public static final ForgeConfigSpec.DoubleValue blood_sect_soul_stone_power;
    public static final ForgeConfigSpec.DoubleValue blood_sect_soul_stone_heal;
    public static final ForgeConfigSpec.DoubleValue blood_sect_soul_stone_owner;
    public static final ForgeConfigSpec.DoubleValue ender_sect_soul_stone_power;
    public static final ForgeConfigSpec.DoubleValue ender_sect_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue ender_sect_soul_stone_damage;
    public static final ForgeConfigSpec.DoubleValue eldritch_sect_soul_stone_power;
    public static final ForgeConfigSpec.DoubleValue eldritch_sect_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue eldritch_sect_soul_stone_damage;
    public static final ForgeConfigSpec.DoubleValue aqua_sect_soul_stone_power;
    public static final ForgeConfigSpec.DoubleValue aqua_sect_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue aqua_sect_soul_stone_chance;
    public static final ForgeConfigSpec.DoubleValue aqua_sect_soul_stone_level;
    public static final ForgeConfigSpec.DoubleValue sound_sect_soul_stone_power;
    public static final ForgeConfigSpec.DoubleValue sound_sect_soul_stone_owner_damage;
    public static final ForgeConfigSpec.DoubleValue sound_sect_soul_stone_damage;
    public static final ForgeConfigSpec.DoubleValue sound_sect_soul_stone_armor;
    public static final ForgeConfigSpec.DoubleValue earth_sect_soul_stone_power;
    public static final ForgeConfigSpec.DoubleValue earth_sect_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue earth_sect_soul_stone_chance;
    public static final ForgeConfigSpec.DoubleValue earth_sect_soul_stone_level;
    public static final ForgeConfigSpec.DoubleValue fantasy_sect_soul_stone_power;
    public static final ForgeConfigSpec.DoubleValue fantasy_sect_soul_stone_fantacy_power;
    public static final ForgeConfigSpec.DoubleValue fantasy_sect_soul_stone_dream_shadow_damage;
    public static final ForgeConfigSpec.DoubleValue fantasy_sect_soul_stone_dream_shadow_damage_resistance;
    public static final ForgeConfigSpec.DoubleValue fantasy_sect_soul_stone_fantasy_ending_damage;
    public static final ForgeConfigSpec.DoubleValue fantasy_sect_soul_stone_fantasy_ending_damage_resistance;
    public static final ForgeConfigSpec.DoubleValue fantasy_sect_soul_stone_damage;
    public static final ForgeConfigSpec.DoubleValue ars_source_soul_stone_re;
    public static final ForgeConfigSpec.DoubleValue ars_source_soul_stone_mana;
    public static final ForgeConfigSpec.DoubleValue ars_source_soul_stone_damage;
    public static final ForgeConfigSpec.DoubleValue drygmy_soul_stone_damage;
    public static final ForgeConfigSpec.DoubleValue drygmy_soul_stone_drop;
    public static final ForgeConfigSpec.DoubleValue whirlisprig_soul_stone_cast;
    public static final ForgeConfigSpec.DoubleValue whirlisprig_soul_stone_food;
    public static final ForgeConfigSpec.DoubleValue starbuncle_soul_stone;
    public static final ForgeConfigSpec.DoubleValue bookwyrm_soul_stone_cast;
    public static final ForgeConfigSpec.DoubleValue bookwyrm_soul_stone_damage;
    public static final ForgeConfigSpec.DoubleValue wixie_soul_stone_up;
    public static final ForgeConfigSpec.DoubleValue wixie_soul_stone_down;
    public static final ForgeConfigSpec.DoubleValue amethyst_golem_soul_stone;
    public static final ForgeConfigSpec.DoubleValue amethyst_golem_soul_stone_level;
    public static final ForgeConfigSpec.DoubleValue archwood_soul_stone_purple;
    public static final ForgeConfigSpec.DoubleValue archwood_soul_stone_green;
    public static final ForgeConfigSpec.DoubleValue archwood_soul_stone_chance;
    public static final ForgeConfigSpec.DoubleValue archwood_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue archwood_soul_stone_red;
    public static final ForgeConfigSpec.DoubleValue archwood_soul_stone_blue;
    public static final ForgeConfigSpec.DoubleValue wilden_soul_stone_re;
    public static final ForgeConfigSpec.DoubleValue wilden_soul_stone_mana;
    public static final ForgeConfigSpec.DoubleValue wilden_soul_stone_damage;
    public static final ForgeConfigSpec.DoubleValue siren_soul_stone;
    public static final ForgeConfigSpec.DoubleValue firenando_soul_stone_cast;
    public static final ForgeConfigSpec.DoubleValue firenando_soul_stone_damage;
    public static final ForgeConfigSpec.DoubleValue ammo_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue ammo_soul_stone_number;
    public static final ForgeConfigSpec.DoubleValue handgun_soul_stone;
    public static final ForgeConfigSpec.DoubleValue rifle_soul_stone_number;
    public static final ForgeConfigSpec.DoubleValue rifle_soul_stone_damage;
    public static final ForgeConfigSpec.DoubleValue rifle_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue sniper_rifle_soul_stone_damage;
    public static final ForgeConfigSpec.DoubleValue sniper_rifle_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue shotgun_soul_stone;
    public static final ForgeConfigSpec.DoubleValue submachine_gun_soul_stone_speed;
    public static final ForgeConfigSpec.DoubleValue submachine_gun_soul_stone_chance;
    public static final ForgeConfigSpec.DoubleValue heavy_machine_gun_soul_stone;
    public static final ForgeConfigSpec.DoubleValue machine_gun_soul_stone;
    public static final ForgeConfigSpec.DoubleValue ignis_soul_stone_give_chance;
    public static final ForgeConfigSpec.DoubleValue ignis_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue ignis_soul_stone_up_chance;
    public static final ForgeConfigSpec.DoubleValue ignis_soul_stone_max_level;
    public static final ForgeConfigSpec.DoubleValue the_leviathan_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue the_leviathan_soul_stone_level;
    public static final ForgeConfigSpec.DoubleValue the_leviathan_soul_stone_armor;
    public static final ForgeConfigSpec.DoubleValue the_leviathan_soul_stone_damage;
    public static final ForgeConfigSpec.DoubleValue maledictus_soul_stone_chance;
    public static final ForgeConfigSpec.DoubleValue maledictus_soul_stone_arrow_chance;
    public static final ForgeConfigSpec.DoubleValue maledictus_soul_stone_heal;
    public static final ForgeConfigSpec.DoubleValue maledictus_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue maledictus_soul_stone_fire_time;
    public static final ForgeConfigSpec.DoubleValue maledictus_soul_stone_cooldown_time;
    public static final ForgeConfigSpec.DoubleValue ender_guardian_soul_stone_chance;
    public static final ForgeConfigSpec.DoubleValue ender_guardian_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue ender_guardian_soul_stone_cooldown;
    public static final ForgeConfigSpec.DoubleValue ancient_remnant_soul_stone_armor;
    public static final ForgeConfigSpec.DoubleValue ancient_remnant_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue ancient_remnant_soul_stone_lvl;
    public static final ForgeConfigSpec.DoubleValue the_harbinger_soul_stone;
    public static final ForgeConfigSpec.DoubleValue netherite_monstrosity_soul_stone_chance;
    public static final ForgeConfigSpec.DoubleValue netherite_monstrosity_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue netherite_monstrosity_soul_stone_max_lvl;
    public static final ForgeConfigSpec.DoubleValue scylla_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue scylla_soul_stone_level;
    public static final ForgeConfigSpec.DoubleValue scylla_soul_stone_damage;
    public static final ForgeConfigSpec.DoubleValue gaia_soul_stone_chance;
    public static final ForgeConfigSpec.DoubleValue gaia_soul_stone_damage;
    public static final ForgeConfigSpec.DoubleValue gaia_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue gaia_soul_stone_heal;
    public static final ForgeConfigSpec.DoubleValue manasteel_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue manasteel_soul_stone_mana;
    public static final ForgeConfigSpec.DoubleValue manasteel_soul_stone_number;
    public static final ForgeConfigSpec.DoubleValue elementium_soul_stone_chance;
    public static final ForgeConfigSpec.DoubleValue elementium_soul_stone_atk;
    public static final ForgeConfigSpec.DoubleValue elementium_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue terrasteel_soul_stone_mana;
    public static final ForgeConfigSpec.ConfigValue<Boolean> terrasteel_soul_stone_left;
    public static final ForgeConfigSpec.DoubleValue zinc_soul_stone_speed;
    public static final ForgeConfigSpec.ConfigValue<Boolean> zinc_soul_stone_use;
    public static final ForgeConfigSpec.ConfigValue<Boolean> andesite_alloy_soul_stone_boot;
    public static final ForgeConfigSpec.ConfigValue<Boolean> andesite_alloy_soul_stone_eyes;
    public static final ForgeConfigSpec.DoubleValue brass_soul_stone_damage;
    public static final ForgeConfigSpec.DoubleValue sturdy_sheet_soul_stone_damage;
    public static final ForgeConfigSpec.ConfigValue<Boolean> cardboard_soul_stone;
    public static final ForgeConfigSpec.ConfigValue<Boolean> blaze_cake_soul_stone_super;
    public static final ForgeConfigSpec.DoubleValue blaze_cake_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue blaze_cake_soul_stone_max_time;
    public static final ForgeConfigSpec.ConfigValue<Boolean> rose_quartz_soul_stone_heat;
    public static final ForgeConfigSpec.DoubleValue rose_quartz_soul_stone_number;
    public static final ForgeConfigSpec.DoubleValue zombie_scepter_soul_stone_strength;
    public static final ForgeConfigSpec.DoubleValue zombie_scepter_soul_stone_hp_boost;
    public static final ForgeConfigSpec.DoubleValue zombie_scepter_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue zombie_scepter_soul_stone_cooldown;
    public static final ForgeConfigSpec.DoubleValue lifedrain_soul_stone_heal;
    public static final ForgeConfigSpec.DoubleValue lifedrain_soul_stone_food;
    public static final ForgeConfigSpec.DoubleValue lifedrain_soul_stone_sat;
    public static final ForgeConfigSpec.DoubleValue fortification_soul_stone_cooldown;
    public static final ForgeConfigSpec.DoubleValue twilight_hydra_soul_stone_range;
    public static final ForgeConfigSpec.DoubleValue twilight_hydra_soul_stone_armor;
    public static final ForgeConfigSpec.DoubleValue twilight_hydra_soul_stone_last_hp;
    public static final ForgeConfigSpec.DoubleValue twilight_hydra_soul_stone_heal;
    public static final ForgeConfigSpec.DoubleValue twilight_hydra_soul_stone_damage;
    public static final ForgeConfigSpec.DoubleValue knight_phantom_soul_stone_armor;
    public static final ForgeConfigSpec.DoubleValue knight_phantom_soul_stone_damage;
    public static final ForgeConfigSpec.DoubleValue minoshroom_soul_stone;
    public static final ForgeConfigSpec.DoubleValue ur_ghast_soul_stone_number;
    public static final ForgeConfigSpec.DoubleValue ur_ghast_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue ur_ghast_soul_stone_armor;
    public static final ForgeConfigSpec.DoubleValue alpha_yeti_soul_stone_hp;
    public static final ForgeConfigSpec.DoubleValue alpha_yeti_soul_stone_range;
    public static final ForgeConfigSpec.DoubleValue alpha_yeti_soul_stone_damage;
    public static final ForgeConfigSpec.DoubleValue alpha_yeti_soul_stone_cooldown;
    public static final ForgeConfigSpec.DoubleValue snow_queen_soul_stone_range;
    public static final ForgeConfigSpec.DoubleValue snow_queen_soul_stone_damage;
    public static final ForgeConfigSpec.DoubleValue snow_queen_soul_stone_cooldown;
    public static final ForgeConfigSpec.DoubleValue naga_soul_stone_speed;
    public static final ForgeConfigSpec.DoubleValue naga_soul_stone_heal;

    public static final ForgeConfigSpec.DoubleValue fire_sect_soul_stone_other;
    public static final ForgeConfigSpec.DoubleValue ice_sect_soul_stone_other;
    public static final ForgeConfigSpec.DoubleValue lightning_sect_soul_stone_other;
    public static final ForgeConfigSpec.DoubleValue evocation_sect_soul_stone_other;
    public static final ForgeConfigSpec.DoubleValue holy_sect_soul_stone_other;
    public static final ForgeConfigSpec.DoubleValue blood_sect_soul_stone_other;
    public static final ForgeConfigSpec.DoubleValue nature_sect_soul_stone_other;
    public static final ForgeConfigSpec.DoubleValue ender_sect_soul_stone_other;
    public static final ForgeConfigSpec.DoubleValue eldritch_sect_soul_stone_other;

    public static final ForgeConfigSpec.DoubleValue aqua_sect_soul_stone_other;
    public static final ForgeConfigSpec.DoubleValue sound_sect_soul_stone_other;
    public static final ForgeConfigSpec.DoubleValue earth_sect_soul_stone_other;
    public static final ForgeConfigSpec.DoubleValue fantacy_sect_soul_stone_other;

    public static final ForgeConfigSpec.DoubleValue ironwood_soul_stone_armor;
    public static final ForgeConfigSpec.DoubleValue ironwood_soul_stone_armor_toughness;
    public static final ForgeConfigSpec.DoubleValue steeleaf_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue steeleaf_soul_stone_number;
    public static final ForgeConfigSpec.DoubleValue fiery_iron_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue fiery_iron_soul_stone_heal;
    public static final ForgeConfigSpec.DoubleValue fluffy_cloud_soul_stone;
    public static final ForgeConfigSpec.DoubleValue twilight_giant_soul_stone_entity;
    public static final ForgeConfigSpec.DoubleValue twilight_giant_soul_stone_block;
    public static final ForgeConfigSpec.DoubleValue quest_ram_soul_stone;

    public static final ForgeConfigSpec.DoubleValue skeletosaurus_soul_stone_atk;
    public static final ForgeConfigSpec.DoubleValue skeletosaurus_soul_stone_armor;
    public static final ForgeConfigSpec.DoubleValue skeletosaurus_soul_stone_knockback_resistance;
    public static final ForgeConfigSpec.DoubleValue withered_abomination_soul_stone_atk;
    public static final ForgeConfigSpec.DoubleValue withered_abomination_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue withered_abomination_soul_stone_level;
    public static final ForgeConfigSpec.DoubleValue lava_eater_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue cloud_golem_soul_stone_damage;
    public static final ForgeConfigSpec.DoubleValue cloud_golem_soul_stone_cooldown;
    public static final ForgeConfigSpec.DoubleValue cloud_golem_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue frostbitten_golem_soul_stone_range;
    public static final ForgeConfigSpec.DoubleValue frostbitten_golem_soul_stone_damage;
    public static final ForgeConfigSpec.DoubleValue frostbitten_golem_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue frostbitten_golem_soul_stone_level;
    public static final ForgeConfigSpec.DoubleValue frostbitten_golem_soul_stone_cooldown;
    public static final ForgeConfigSpec.DoubleValue ancient_guardian_soul_stone_fixed_damage;
    public static final ForgeConfigSpec.DoubleValue ancient_guardian_soul_stone_damage;
    public static final ForgeConfigSpec.DoubleValue ancient_guardian_soul_stone_chance;
    public static final ForgeConfigSpec.DoubleValue ancient_guardian_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue ancient_guardian_soul_stone_cooldown;
    public static final ForgeConfigSpec.DoubleValue ancient_guardian_soul_stone_hp;
    public static final ForgeConfigSpec.DoubleValue ancient_guardian_soul_stone_armor;
    public static final ForgeConfigSpec.DoubleValue posessed_paladin_soul_stone_chance;
    public static final ForgeConfigSpec.DoubleValue posessed_paladin_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue posessed_paladin_soul_stone_range;
    public static final ForgeConfigSpec.DoubleValue posessed_paladin_soul_stone_level;
    public static final ForgeConfigSpec.DoubleValue dune_sentinel_soul_stone_up;
    public static final ForgeConfigSpec.DoubleValue dune_sentinel_soul_stone_down;
    public static final ForgeConfigSpec.DoubleValue endersent_soul_stone;
    public static final ForgeConfigSpec.DoubleValue shulker_mimic_soul_stone_chance;
    public static final ForgeConfigSpec.DoubleValue shulker_mimic_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue shulker_mimic_soul_stone_level;
    public static final ForgeConfigSpec.DoubleValue shulker_mimic_soul_stone_cooldown;
    public static final ForgeConfigSpec.DoubleValue overgrown_colossus_soul_stone_time;
    public static final ForgeConfigSpec.DoubleValue overgrown_colossus_soul_stone_level;

    public static final ForgeConfigSpec.DoubleValue ectoplasm_soul_stone;
    public static final ForgeConfigSpec.DoubleValue goety_focus_soul_stone;
    public static final ForgeConfigSpec.DoubleValue order_about_soul_stone_damage;
    public static final ForgeConfigSpec.DoubleValue escort_soul_stone;
    public static final ForgeConfigSpec.DoubleValue brew_soul_stone_chance_a;
    public static final ForgeConfigSpec.DoubleValue brew_soul_stone_chance_b;
    public static final ForgeConfigSpec.DoubleValue legion_soul_stone_hp;
    public static final ForgeConfigSpec.DoubleValue legion_soul_stone_atk;
    public static final ForgeConfigSpec.DoubleValue legion_soul_stone_speed;
    public static final ForgeConfigSpec.DoubleValue goety_dark_soul_stone_fire;
    public static final ForgeConfigSpec.DoubleValue goety_dark_soul_stone_magic;


    static {
        //祝福
        BUILDER.push("base");
        goety_dark_soul_stone_magic = BUILDER.comment("诡暗魂石魔法伤害减免").defineInRange("goety_dark_soul_stone_magic",0.15,0,2147483647);
        goety_dark_soul_stone_fire = BUILDER.comment("诡暗魂石火、爆伤害减免").defineInRange("goety_dark_soul_stone_fire",0.375,0,2147483647);
        legion_soul_stone_speed = BUILDER.comment("军团魂石移速属性提升").defineInRange("legion_soul_stone_speed",0.1,0,2147483647);
        legion_soul_stone_atk = BUILDER.comment("军团魂石攻击属性提升").defineInRange("legion_soul_stone_atk",0.1,0,2147483647);
        legion_soul_stone_hp = BUILDER.comment("军团魂石生命属性提升").defineInRange("legion_soul_stone_hp",0.1,0,2147483647);
        brew_soul_stone_chance_b = BUILDER.comment("药酿魂石药水几率").defineInRange("brew_soul_stone_chance_b",0.2,0,2147483647);
        brew_soul_stone_chance_a = BUILDER.comment("药酿魂石药酿几率").defineInRange("brew_soul_stone_chance_a",0.1,0,2147483647);
        escort_soul_stone = BUILDER.comment("护卫魂石").defineInRange("escort_soul_stone",0.15,0,2147483647);
        order_about_soul_stone_damage = BUILDER.comment("驱役魂石伤害增幅").defineInRange("order_about_soul_stone_damage",0.15,0,2147483647);
        goety_focus_soul_stone = BUILDER.comment("聚晶魂石数额").defineInRange("goety_focus_soul_stone",1.0,0,2147483647);
        ectoplasm_soul_stone = BUILDER.comment("灵质魂石数额").defineInRange("ectoplasm_soul_stone",100.0,0,2147483647);

        overgrown_colossus_soul_stone_level = BUILDER.comment("蔓生巨像魂石等级").defineInRange("overgrown_colossus_soul_stone_level",1.0,0,2147483647);
        overgrown_colossus_soul_stone_time = BUILDER.comment("蔓生巨像魂石时长").defineInRange("overgrown_colossus_soul_stone_time",5.0,0,2147483647);
        shulker_mimic_soul_stone_cooldown = BUILDER.comment("潜影拟态者魂石冷却").defineInRange("shulker_mimic_soul_stone_cooldown",4.0,0,2147483647);
        shulker_mimic_soul_stone_level = BUILDER.comment("潜影拟态者魂石等级").defineInRange("shulker_mimic_soul_stone_level",1.0,0,2147483647);
        shulker_mimic_soul_stone_time = BUILDER.comment("潜影拟态者魂石时长").defineInRange("shulker_mimic_soul_stone_time",3.0,0,2147483647);
        shulker_mimic_soul_stone_chance = BUILDER.comment("潜影拟态者魂石几率").defineInRange("shulker_mimic_soul_stone_chance",0.3,0,2147483647);
        endersent_soul_stone = BUILDER.comment("末影遣使魂石减伤").defineInRange("endersent_soul_stone",0.25,0,2147483647);
        dune_sentinel_soul_stone_down = BUILDER.comment("沙丘哨兵魂石减伤").defineInRange("dune_sentinel_soul_stone_down",0.25,0,2147483647);
        dune_sentinel_soul_stone_up = BUILDER.comment("沙丘哨兵魂石增伤").defineInRange("dune_sentinel_soul_stone_up",0.15,0,2147483647);
        posessed_paladin_soul_stone_level = BUILDER.comment("魄攫圣骑魂石等级").defineInRange("posessed_paladin_soul_stone_level",1.0,0,2147483647);
        posessed_paladin_soul_stone_range = BUILDER.comment("魄攫圣骑魂石范围").defineInRange("posessed_paladin_soul_stone_range",21.0,0,2147483647);
        posessed_paladin_soul_stone_time = BUILDER.comment("魄攫圣骑魂石时间").defineInRange("posessed_paladin_soul_stone_time",3.0,0,2147483647);
        posessed_paladin_soul_stone_chance = BUILDER.comment("魄攫圣骑魂石几率").defineInRange("posessed_paladin_soul_stone_chance",0.5,0,2147483647);
        ancient_guardian_soul_stone_armor = BUILDER.comment("荒古守卫者魂石护甲提升数额").defineInRange("ancient_guardian_soul_stone_armor",0.25,0,2147483647);
        ancient_guardian_soul_stone_hp = BUILDER.comment("荒古守卫者魂石护甲提升阈值").defineInRange("ancient_guardian_soul_stone_hp",0.5,0,2147483647);
        ancient_guardian_soul_stone_cooldown = BUILDER.comment("荒古守卫者魂石冷却").defineInRange("ancient_guardian_soul_stone_cooldown",0.2,0,2147483647);
        ancient_guardian_soul_stone_time = BUILDER.comment("荒古守卫者魂石BUFF时间").defineInRange("ancient_guardian_soul_stone_time",3.0,0,2147483647);
        ancient_guardian_soul_stone_chance = BUILDER.comment("荒古守卫者魂石概率").defineInRange("ancient_guardian_soul_stone_chance",0.5,0,2147483647);
        ancient_guardian_soul_stone_damage = BUILDER.comment("荒古守卫者魂石百分比伤害").defineInRange("ancient_guardian_soul_stone_damage",0.25,0,2147483647);
        ancient_guardian_soul_stone_fixed_damage = BUILDER.comment("荒古守卫者魂石固定伤害").defineInRange("ancient_guardian_soul_stone_fixed_damage",5.0,0,2147483647);
        frostbitten_golem_soul_stone_cooldown = BUILDER.comment("霜冻傀儡魂石冷却").defineInRange("frostbitten_golem_soul_stone_cooldown",0.2,0,2147483647);
        frostbitten_golem_soul_stone_level = BUILDER.comment("霜冻傀儡魂石等级").defineInRange("frostbitten_golem_soul_stone_level",1.0,0,2147483647);
        frostbitten_golem_soul_stone_time = BUILDER.comment("霜冻傀儡魂石时长").defineInRange("frostbitten_golem_soul_stone_time",3.0,0,2147483647);
        frostbitten_golem_soul_stone_damage = BUILDER.comment("霜冻傀儡魂石伤害").defineInRange("frostbitten_golem_soul_stone_damage",0.2,0,2147483647);
        frostbitten_golem_soul_stone_range = BUILDER.comment("霜冻傀儡魂石范围").defineInRange("frostbitten_golem_soul_stone_range",7.0,0,2147483647);
        cloud_golem_soul_stone_time = BUILDER.comment("湫渃云魔魂石无敌时间延长").defineInRange("cloud_golem_soul_stone_time",0.5,0,2147483647);
        cloud_golem_soul_stone_cooldown = BUILDER.comment("湫渃云魔魂石冷却").defineInRange("cloud_golem_soul_stone_cooldown",0.2,0,2147483647);
        cloud_golem_soul_stone_damage = BUILDER.comment("湫渃云魔魂石雷伤").defineInRange("cloud_golem_soul_stone_damage",0.35,0,2147483647);
        lava_eater_soul_stone_time = BUILDER.comment("熔岩食者魂石燃烧时长").defineInRange("lava_eater_soul_stone_time",5.0,0,2147483647);
        withered_abomination_soul_stone_level = BUILDER.comment("凋灵恶煞魂石凋零等级").defineInRange("withered_abomination_soul_stone_level",1.0,0,2147483647);
        withered_abomination_soul_stone_time = BUILDER.comment("凋灵恶煞魂石凋零时长").defineInRange("withered_abomination_soul_stone_time",5.0,0,2147483647);
        withered_abomination_soul_stone_atk = BUILDER.comment("凋灵恶煞魂石攻击").defineInRange("withered_abomination_soul_stone_atk",0.125,0,2147483647);
        skeletosaurus_soul_stone_knockback_resistance = BUILDER.comment("骷髅蜥龙魂石击退抗性").defineInRange("skeletosaurus_soul_stone_knockback_resistance",0.2,0,2147483647);
        skeletosaurus_soul_stone_armor = BUILDER.comment("骷髅蜥龙魂石护甲").defineInRange("skeletosaurus_soul_stone_armor",2.0,0,2147483647);
        skeletosaurus_soul_stone_atk = BUILDER.comment("骷髅蜥龙魂石攻击").defineInRange("skeletosaurus_soul_stone_atk",0.075,0,2147483647);
        quest_ram_soul_stone = BUILDER.comment("迷题羊魂石减伤").defineInRange("quest_ram_soul_stone",0.15,0,2147483647);
        twilight_giant_soul_stone_block = BUILDER.comment("巨人魂石实体距离").defineInRange("twilight_giant_soul_stone_block",2.5,0,2147483647);
        twilight_giant_soul_stone_entity = BUILDER.comment("巨人魂石实体距离").defineInRange("twilight_giant_soul_stone_entity",2.5,0,2147483647);
        fluffy_cloud_soul_stone = BUILDER.comment("浮云魂石减伤").defineInRange("fluffy_cloud_soul_stone",0.15,0,2147483647);
        fiery_iron_soul_stone_heal = BUILDER.comment("炽铁魂石回血比例").defineInRange("fiery_iron_soul_stone_heal",0.1,0,2147483647);
        fiery_iron_soul_stone_time = BUILDER.comment("炽铁魂石燃烧时长").defineInRange("fiery_iron_soul_stone_time",10.0,0,2147483647);
        steeleaf_soul_stone_number = BUILDER.comment("钢叶魂石数额").defineInRange("steeleaf_soul_stone_number",1.0,0,2147483647);
        steeleaf_soul_stone_time = BUILDER.comment("钢叶魂石间隔").defineInRange("steeleaf_soul_stone_time",3.0,0,2147483647);
        ironwood_soul_stone_armor_toughness = BUILDER.comment("铁木魂石护甲韧性").defineInRange("ironwood_soul_stone_armor_toughness",1.0,0,2147483647);
        ironwood_soul_stone_armor = BUILDER.comment("铁木魂石护甲").defineInRange("ironwood_soul_stone_armor",3.0,0,2147483647);

        fantacy_sect_soul_stone_other = BUILDER.comment("梦幻学派魂石外学派转化率").defineInRange("fantacy_sect_soul_stone_other",0.3,0,2147483647);
        earth_sect_soul_stone_other = BUILDER.comment("岩土学派魂石外学派转化率").defineInRange("earth_sect_soul_stone_other",0.3,0,2147483647);
        sound_sect_soul_stone_other = BUILDER.comment("律灵学派魂石外学派转化率").defineInRange("sound_sect_soul_stone_other",0.3,0,2147483647);
        aqua_sect_soul_stone_other = BUILDER.comment("源流学派魂石外学派转化率").defineInRange("aqua_sect_soul_stone_other",0.3,0,2147483647);

        eldritch_sect_soul_stone_other = BUILDER.comment("邪术学派魂石外学派转化率").defineInRange("eldritch_sect_soul_stone_other",0.3,0,2147483647);
        ender_sect_soul_stone_other = BUILDER.comment("末影学派魂石外学派转化率").defineInRange("ender_sect_soul_stone_other",0.3,0,2147483647);
        nature_sect_soul_stone_other = BUILDER.comment("自然学派魂石外学派转化率").defineInRange("nature_sect_soul_stone_other",0.3,0,2147483647);
        blood_sect_soul_stone_other = BUILDER.comment("猩红学派魂石外学派转化率").defineInRange("blood_sect_soul_stone_other",0.3,0,2147483647);
        holy_sect_soul_stone_other = BUILDER.comment("神圣学派魂石外学派转化率").defineInRange("holy_sect_soul_stone_other",0.3,0,2147483647);
        evocation_sect_soul_stone_other = BUILDER.comment("唤魔学派魂石外学派转化率").defineInRange("evocation_sect_soul_stone_other",0.3,0,2147483647);
        lightning_sect_soul_stone_other = BUILDER.comment("雷霆学派魂石外学派转化率").defineInRange("lightning_sect_soul_stone_other",0.3,0,2147483647);
        ice_sect_soul_stone_other = BUILDER.comment("冰霜学派魂石外学派转化率").defineInRange("ice_sect_soul_stone_other",0.3,0,2147483647);
        fire_sect_soul_stone_other = BUILDER.comment("炽焰学派魂石外学派转化率").defineInRange("fire_sect_soul_stone_other",0.3,0,2147483647);

        naga_soul_stone_heal = BUILDER.comment("娜迦魂石治疗增幅").defineInRange("naga_soul_stone_heal",0.2,0,2147483647);
        naga_soul_stone_speed = BUILDER.comment("娜迦魂石移速").defineInRange("naga_soul_stone_speed",0.1,0,2147483647);
        snow_queen_soul_stone_cooldown = BUILDER.comment("冰雪女王魂石冷却").defineInRange("snow_queen_soul_stone_cooldown",0.2,0,2147483647);
        snow_queen_soul_stone_damage = BUILDER.comment("冰雪女王魂石伤害").defineInRange("snow_queen_soul_stone_damage",0.25,0,2147483647);
        snow_queen_soul_stone_range = BUILDER.comment("冰雪女王魂石范围").defineInRange("snow_queen_soul_stone_range",9.0,0,2147483647);
        alpha_yeti_soul_stone_cooldown = BUILDER.comment("雪怪魂石冷却").defineInRange("alpha_yeti_soul_stone_cooldown",0.2,0,2147483647);
        alpha_yeti_soul_stone_damage = BUILDER.comment("雪怪魂石伤害").defineInRange("alpha_yeti_soul_stone_damage",0.15,0,2147483647);
        alpha_yeti_soul_stone_range = BUILDER.comment("雪怪魂石范围").defineInRange("alpha_yeti_soul_stone_range",7.0,0,2147483647);
        alpha_yeti_soul_stone_hp = BUILDER.comment("雪怪魂石HP").defineInRange("alpha_yeti_soul_stone_hp",0.05,0,2147483647);
        ur_ghast_soul_stone_armor = BUILDER.comment("暮初恶魂魂石减伤").defineInRange("ur_ghast_soul_stone_armor",0.2,0,2147483647);
        ur_ghast_soul_stone_time = BUILDER.comment("暮初恶魂魂石减伤时长").defineInRange("ur_ghast_soul_stone_time",2.0,0,2147483647);
        ur_ghast_soul_stone_number = BUILDER.comment("暮初恶魂魂石护甲穿透").defineInRange("ur_ghast_soul_stone_number",0.072,0,2147483647);
        minoshroom_soul_stone = BUILDER.comment("米诺菇魂石护甲穿透").defineInRange("minoshroom_soul_stone",0.2,0,2147483647);
        knight_phantom_soul_stone_damage = BUILDER.comment("幻影骑士魂石护甲增伤").defineInRange("knight_phantom_soul_stone_damage",0.15,0,2147483647);
        knight_phantom_soul_stone_armor = BUILDER.comment("幻影骑士魂石护甲阈值").defineInRange("knight_phantom_soul_stone_armor",0.0,0,2147483647);
        twilight_hydra_soul_stone_damage = BUILDER.comment("九头蛇魂石最高增伤").defineInRange("twilight_hydra_soul_stone_damage",0.3,0,2147483647);
        twilight_hydra_soul_stone_heal = BUILDER.comment("九头蛇魂石最多回血").defineInRange("twilight_hydra_soul_stone_heal",1.0,0,2147483647);
        twilight_hydra_soul_stone_last_hp = BUILDER.comment("九头蛇魂石生命阈值").defineInRange("twilight_hydra_soul_stone_last_hp",0.1,0,2147483647);
        twilight_hydra_soul_stone_armor = BUILDER.comment("九头蛇魂石减伤数额").defineInRange("twilight_hydra_soul_stone_armor",0.5,0,2147483647);
        twilight_hydra_soul_stone_range = BUILDER.comment("九头蛇魂石减伤范围").defineInRange("twilight_hydra_soul_stone_range",21.0,0,2147483647);
        fortification_soul_stone_cooldown = BUILDER.comment("光巫魂石僵尸冷却时间").defineInRange("fortification_soul_stone_cooldown",60.0,0,2147483647);
        lifedrain_soul_stone_sat = BUILDER.comment("血巫魂石伤害饱和转换比例").defineInRange("lifedrain_soul_stone_sat",0.05,0,2147483647);
        lifedrain_soul_stone_food = BUILDER.comment("血巫魂石伤害饥饿转换比例").defineInRange("lifedrain_soul_stone_food",0.05,0,2147483647);
        lifedrain_soul_stone_heal = BUILDER.comment("血巫魂石伤害回血转换比例").defineInRange("lifedrain_soul_stone_heal",0.05,0,2147483647);
        zombie_scepter_soul_stone_cooldown = BUILDER.comment("尸巫魂石僵尸召唤间隔时间").defineInRange("zombie_scepter_soul_stone_cooldown",20.0,0,2147483647);
        zombie_scepter_soul_stone_time = BUILDER.comment("尸巫魂石僵尸BUFF时间").defineInRange("zombie_scepter_soul_stone_time",30.0,0,2147483647);
        zombie_scepter_soul_stone_hp_boost = BUILDER.comment("尸巫魂石僵尸生命提升等级").defineInRange("zombie_scepter_soul_stone_hp_boost",1.0,0,255);
        zombie_scepter_soul_stone_strength = BUILDER.comment("尸巫魂石僵尸力量等级").defineInRange("zombie_scepter_soul_stone_strength",1.0,0,255);
        rose_quartz_soul_stone_number = BUILDER.comment("玫瑰石英魂石耐久回复").defineInRange("rose_quartz_soul_stone_number",1.0,0,2147483647);
        rose_quartz_soul_stone_heat = BUILDER.comment("玫瑰石英魂石头盔能力").define("rose_quartz_soul_stone_heat",true);
        blaze_cake_soul_stone_time = BUILDER.comment("烈焰蛋糕魂石燃烧时间").defineInRange("blaze_cake_soul_stone_time",60.0,0,2147483647);
        blaze_cake_soul_stone_max_time = BUILDER.comment("烈焰蛋糕魂石最高燃烧时间").defineInRange("blaze_cake_soul_stone_max_time",180.0,0,2147483647);
        blaze_cake_soul_stone_super = BUILDER.comment("烈焰蛋糕魂石右键时是否是超级燃烧(目前无法进行超级燃烧，所以只能正常燃起来)").define("blaze_cake_soul_stone_super",false);
        cardboard_soul_stone = BUILDER.comment("纸板魂石功能").define("cardboard_soul_stone",true);
        sturdy_sheet_soul_stone_damage = BUILDER.comment("坚固板魂石机器伤害减免").defineInRange("sturdy_sheet_soul_stone_damage",1.0,0,2147483647);
        brass_soul_stone_damage = BUILDER.comment("黄铜魂石机器伤害减免").defineInRange("brass_soul_stone_damage",0.9,0,2147483647);
        andesite_alloy_soul_stone_boot = BUILDER.comment("安山合金魂石潜水靴功能").define("andesite_alloy_soul_stone_boot",true);
        andesite_alloy_soul_stone_eyes = BUILDER.comment("安山合金魂石护目镜功能").define("andesite_alloy_soul_stone_eyes",true);
        zinc_soul_stone_use = BUILDER.comment("锌魂石是否可以不消耗饥饿度使用曲柄").define("zinc_soul_stone_use",true);
        zinc_soul_stone_speed = BUILDER.comment("锌魂石挖掘速度").defineInRange("zinc_soul_stone_speed",0.5,0,2147483647);
        terrasteel_soul_stone_left = BUILDER.comment("泰拉钢魂石是否允许左键释放光束").define("terrasteel_soul_stone_left",true);
        terrasteel_soul_stone_mana = BUILDER.comment("泰拉钢魂石魔力恢复数额").defineInRange("terrasteel_soul_stone_mana",20.0,0,2147483647);
        elementium_soul_stone_time = BUILDER.comment("精灵钢魂石DEBUFF时长").defineInRange("elementium_soul_stone_time",3.0,0,2147483647);
        elementium_soul_stone_atk = BUILDER.comment("精灵钢魂石攻击力基础").defineInRange("elementium_soul_stone_atk",0.5,0,2147483647);
        elementium_soul_stone_chance = BUILDER.comment("精灵钢魂石概率").defineInRange("elementium_soul_stone_chance",0.5,0,2147483647);
        manasteel_soul_stone_number = BUILDER.comment("魔力钢魂石耐久回复数额").defineInRange("manasteel_soul_stone_number",1.0,0,2147483647);
        manasteel_soul_stone_mana = BUILDER.comment("魔力钢魂石消耗").defineInRange("manasteel_soul_stone_mana",70.0,0,2147483647);
        manasteel_soul_stone_time = BUILDER.comment("魔力钢魂石间隔").defineInRange("manasteel_soul_stone_time",2.0,0.05,2147483647);
        gaia_soul_stone_heal = BUILDER.comment("盖亚魂石回血数额").defineInRange("gaia_soul_stone_heal",1.0,0,2147483647);
        gaia_soul_stone_time = BUILDER.comment("盖亚魂石回血间隔").defineInRange("gaia_soul_stone_time",2.0,0.05,2147483647);
        gaia_soul_stone_damage = BUILDER.comment("盖亚魂石暴击伤害").defineInRange("gaia_soul_stone_damage",1.5,0,2147483647);
        gaia_soul_stone_chance = BUILDER.comment("盖亚魂石暴击概率").defineInRange("gaia_soul_stone_chance",0.5,0,2147483647);
        scylla_soul_stone_damage = BUILDER.comment("斯库拉魂石潮湿增伤").defineInRange("scylla_soul_stone_damage",0.1,0,2147483647);
        scylla_soul_stone_level = BUILDER.comment("斯库拉魂石潮湿等级").defineInRange("scylla_soul_stone_level",1.0,0,2147483647);
        scylla_soul_stone_time = BUILDER.comment("斯库拉魂石潮湿时间").defineInRange("scylla_soul_stone_time",10.0,0,2147483647);
        netherite_monstrosity_soul_stone_max_lvl = BUILDER.comment("下界合金巨兽最大等级").defineInRange("netherite_monstrosity_soul_stone_max_lvl",3.0,0,2147483647);
        netherite_monstrosity_soul_stone_time = BUILDER.comment("下界合金巨兽魂石BUFF时长").defineInRange("netherite_monstrosity_soul_stone_time",10.0,0,2147483647);
        netherite_monstrosity_soul_stone_chance = BUILDER.comment("下界合金巨兽魂石概率").defineInRange("netherite_monstrosity_soul_stone_chance",0.2,0,2147483647);
        the_harbinger_soul_stone = BUILDER.comment("先驱者魂石无敌时间削减").defineInRange("the_harbinger_soul_stone",0.5,0,2147483647);
        ancient_remnant_soul_stone_lvl = BUILDER.comment("远古遗魂魂石骨裂等级").defineInRange("ancient_remnant_soul_stone_lvl",1.0,0,2147483647);
        ancient_remnant_soul_stone_time = BUILDER.comment("远古遗魂魂石骨裂时间").defineInRange("ancient_remnant_soul_stone_time",5.0,0,2147483647);
        ancient_remnant_soul_stone_armor = BUILDER.comment("远古遗魂魂石护甲韧性").defineInRange("ancient_remnant_soul_stone_armor",3.0,0,2147483647);
        ender_guardian_soul_stone_cooldown = BUILDER.comment("末影守卫魂石冷却").defineInRange("ender_guardian_soul_stone_cooldown",5.0,0,2147483647);
        ender_guardian_soul_stone_time = BUILDER.comment("末影守卫魂石时间").defineInRange("ender_guardian_soul_stone_time",2.0,0,2147483647);
        ender_guardian_soul_stone_chance = BUILDER.comment("末影守卫魂石概率").defineInRange("ender_guardian_soul_stone_chance",0.25,0,2147483647);
        maledictus_soul_stone_cooldown_time = BUILDER.comment("咒翼灵骸魂石冷却时间").defineInRange("maledictus_soul_stone_cooldown_time",300.0,0,2147483647);
        maledictus_soul_stone_fire_time = BUILDER.comment("咒翼灵骸魂石防火时间").defineInRange("maledictus_soul_stone_fire_time",10.0,0,2147483647);
        maledictus_soul_stone_time = BUILDER.comment("咒翼灵骸魂石复活无敌").defineInRange("maledictus_soul_stone_time",5.0,0,2147483647);
        maledictus_soul_stone_heal = BUILDER.comment("咒翼灵骸魂石复活治疗量").defineInRange("maledictus_soul_stone_heal",0.2,0,2147483647);
        maledictus_soul_stone_arrow_chance = BUILDER.comment("咒翼灵骸魂石弹射物免伤额外概率").defineInRange("maledictus_soul_stone_arrow_chance",0.15,0,2147483647);
        maledictus_soul_stone_chance = BUILDER.comment("咒翼灵骸魂石免伤概率").defineInRange("maledictus_soul_stone_chance",0.05,0,2147483647);
        the_leviathan_soul_stone_damage = BUILDER.comment("焰魔魂石水下增伤").defineInRange("the_leviathan_soul_stone_damage",0.1,0,2147483647);
        the_leviathan_soul_stone_armor = BUILDER.comment("焰魔魂石水上减伤").defineInRange("the_leviathan_soul_stone_armor",0.2,0,2147483647);
        the_leviathan_soul_stone_level = BUILDER.comment("利维坦魂石等级").defineInRange("the_leviathan_soul_stone_level",3.0,0,2147483647);
        the_leviathan_soul_stone_time = BUILDER.comment("利维坦魂石时间").defineInRange("the_leviathan_soul_stone_time",5.0,0,2147483647);
        ignis_soul_stone_give_chance = BUILDER.comment("焰魔魂石基础概率").defineInRange("ignis_soul_stone_give_chance",0.6,0,2147483647);
        ignis_soul_stone_time = BUILDER.comment("焰魔魂石等级时间").defineInRange("ignis_soul_stone_time",10.0,0,2147483647);
        ignis_soul_stone_up_chance = BUILDER.comment("焰魔魂石等级提升概率").defineInRange("ignis_soul_stone_up_chance",0.3,0,2147483647);
        ignis_soul_stone_max_level = BUILDER.comment("焰魔魂石最高等级").defineInRange("ignis_soul_stone_max_level", 5.0,0,2147483647);
        machine_gun_soul_stone = BUILDER.comment("机枪魂石增伤").defineInRange("machine_gun_soul_stone",0.1F,0,2147483647);
        heavy_machine_gun_soul_stone = BUILDER.comment("重型枪械魂石概率").defineInRange("heavy_machine_gun_soul_stone",0.5F,0,2147483647);
        submachine_gun_soul_stone_chance = BUILDER.comment("冲锋枪魂石概率").defineInRange("submachine_gun_soul_stone_chance",0.25F,0,2147483647);
        submachine_gun_soul_stone_speed = BUILDER.comment("冲锋枪魂石移速").defineInRange("submachine_gun_soul_stone_speed",0.1F,0,2147483647);
        shotgun_soul_stone = BUILDER.comment("霰弹枪魂石破甲").defineInRange("shotgun_soul_stone",0.25F,0,2147483647);
        sniper_rifle_soul_stone_damage = BUILDER.comment("狙击枪魂石最高增伤").defineInRange("sniper_rifle_soul_stone_damage",0.3,0,2147483647);
        sniper_rifle_soul_stone_time = BUILDER.comment("狙击枪魂石最长间隔").defineInRange("sniper_rifle_soul_stone_time",3F,0,2147483647);
        rifle_soul_stone_time = BUILDER.comment("步枪魂石最长间隔").defineInRange("rifle_soul_stone_time",5.0,0,2147483647);
        rifle_soul_stone_damage = BUILDER.comment("步枪魂石最高增伤").defineInRange("rifle_soul_stone_damage",0.15,0,2147483647);
        rifle_soul_stone_number = BUILDER.comment("步枪魂石最高连射次数").defineInRange("rifle_soul_stone_number",10F,0,2147483647);
        handgun_soul_stone = BUILDER.comment("手枪魂石爆头伤害").defineInRange("handgun_soul_stone",0.5,0,2147483647);
        ammo_soul_stone_number = BUILDER.comment("弹药魂石弹药数").defineInRange("ammo_soul_stone_number",1F,1,2147483647);
        ammo_soul_stone_time = BUILDER.comment("弹药魂石间隔").defineInRange("ammo_soul_stone_time",5,0.05,2147483647);
        firenando_soul_stone_damage = BUILDER.comment("烈焰加农魂石魔符伤害").defineInRange("firenando_soul_stone_damage",1,0F,2147483647);
        firenando_soul_stone_cast = BUILDER.comment("烈焰加农魂石减免").defineInRange("firenando_soul_stone_cast",10,0F,2147483647);
        siren_soul_stone = BUILDER.comment("塞壬魂石").defineInRange("siren_soul_stone",1,0F,2147483647);
        wilden_soul_stone_damage = BUILDER.comment("荒野魂石伤害").defineInRange("wilden_soul_stone_damage",2,0F,2147483647);
        wilden_soul_stone_mana = BUILDER.comment("荒野魂石最大魔源").defineInRange("wilden_soul_stone_mana",0.2,0F,2147483647);
        wilden_soul_stone_re = BUILDER.comment("荒野魂石再生").defineInRange("wilden_soul_stone_re",0.1,0F,2147483647);
        archwood_soul_stone_red = BUILDER.comment("至高木魂石爆炸等级").defineInRange("archwood_soul_stone_red",1,0F,2147483647);
        archwood_soul_stone_blue = BUILDER.comment("至高木魂石冻结等级").defineInRange("archwood_soul_stone_blue",1,0F,2147483647);
        archwood_soul_stone_time = BUILDER.comment("至高木魂石debuff时长").defineInRange("archwood_soul_stone_time",5,0F,2147483647);
        archwood_soul_stone_chance = BUILDER.comment("至高木魂石Debuff概率").defineInRange("archwood_soul_stone_chance",0.1,0F,2147483647);
        archwood_soul_stone_green = BUILDER.comment("至高木魂石康复等级").defineInRange("archwood_soul_stone_green",1,0F,2147483647);
        archwood_soul_stone_purple = BUILDER.comment("至高木魂石护盾等级").defineInRange("archwood_soul_stone_purple",1,0F,2147483647);
        amethyst_golem_soul_stone_level = BUILDER.comment("紫水晶傀儡魂石状态等级").defineInRange("amethyst_golem_soul_stone_level",1,0F,2147483647);
        amethyst_golem_soul_stone = BUILDER.comment("紫水晶傀儡魂石击退抗性").defineInRange("amethyst_golem_soul_stone",0.3,0F,2147483647);
        wixie_soul_stone_down = BUILDER.comment("薇克精魂石负面状态时长降低").defineInRange("wixie_soul_stone_down",0.3,0F,2147483647);
        wixie_soul_stone_up = BUILDER.comment("薇克精魂石正面状态时长提升").defineInRange("wixie_soul_stone_up",0.2,0F,2147483647);
        bookwyrm_soul_stone_damage = BUILDER.comment("书龙魂石魔符伤害").defineInRange("bookwyrm_soul_stone_damage",2,0F,2147483647);
        bookwyrm_soul_stone_cast = BUILDER.comment("书龙魂石减免").defineInRange("bookwyrm_soul_stone_cast",20,0F,2147483647);
        starbuncle_soul_stone = BUILDER.comment("星宝石兽魂石移速").defineInRange("starbuncle_soul_stone",0.4,0F,2147483647);
        whirlisprig_soul_stone_cast = BUILDER.comment("风转草魂石消耗减免").defineInRange("whirlisprig_soul_stone_cast",10,0F,2147483647);
        whirlisprig_soul_stone_food = BUILDER.comment("风转草魂石额外回复饱食度").defineInRange("whirlisprig_soul_stone_food",0.5,0F,2147483647);
        drygmy_soul_stone_drop = BUILDER.comment("德格米魂石额外掉落物").defineInRange("drygmy_soul_stone_drop",1,0F,2147483647);
        drygmy_soul_stone_damage = BUILDER.comment("德格米魂石魔艺伤害").defineInRange("drygmy_soul_stone_damage",1,0F,2147483647);
        ars_source_soul_stone_damage = BUILDER.comment("魔源魂石魔源伤害").defineInRange("ars_source_soul_stone_damage",1,0F,2147483647);
        ars_source_soul_stone_mana = BUILDER.comment("魔源魂石最大魔源").defineInRange("ars_source_soul_stone_mana",30,0F,2147483647);
        ars_source_soul_stone_re = BUILDER.comment("魔源魂石魔源再生").defineInRange("ars_source_soul_stone_re",1,0F,2147483647);
        fantasy_sect_soul_stone_damage = BUILDER.comment("梦幻学派魂石法术增幅").defineInRange("fantasy_sect_soul_stone_damage",0.2,0F,2147483647);
        fantasy_sect_soul_stone_fantasy_ending_damage_resistance = BUILDER.comment("梦幻学派魂石梦终抗性").defineInRange("fantasy_sect_soul_stone_fantasy_ending_damage_resistance",0.17,0F,2147483647);
        fantasy_sect_soul_stone_fantasy_ending_damage = BUILDER.comment("梦幻学派魂石梦终伤害").defineInRange("fantasy_sect_soul_stone_fantasy_ending_damage",3,0F,2147483647);
        fantasy_sect_soul_stone_dream_shadow_damage_resistance = BUILDER.comment("梦幻学派魂石梦影抗性").defineInRange("fantasy_sect_soul_stone_dream_shadow_damage_resistance",0.15,0F,2147483647);
        fantasy_sect_soul_stone_dream_shadow_damage = BUILDER.comment("梦幻学派魂石梦影伤害").defineInRange("fantasy_sect_soul_stone_dream_shadow_damage",4,0F,2147483647);
        fantasy_sect_soul_stone_fantacy_power = BUILDER.comment("梦幻学派魂石梦幻法强").defineInRange("fantasy_sect_soul_stone_fantacy_power",0.275,0F,2147483647);
        fantasy_sect_soul_stone_power = BUILDER.comment("梦幻学派魂石通用法强").defineInRange("fantasy_sect_soul_stone_power",0.2,0F,2147483647);
        earth_sect_soul_stone_power = BUILDER.comment("岩土学派魂石法强").defineInRange("earth_sect_soul_stone_power",0.1,0F,2147483647);
        earth_sect_soul_stone_time = BUILDER.comment("岩土学派魂石buff时间").defineInRange("earth_sect_soul_stone_time",5,0F,2147483647);
        earth_sect_soul_stone_chance = BUILDER.comment("岩土学派魂石buff提升概率").defineInRange("earth_sect_soul_stone_chance",0.3,0F,2147483647);
        earth_sect_soul_stone_level = BUILDER.comment("岩土学派魂石最高buff提升等级").defineInRange("earth_sect_soul_stone_level",10,0F,2147483647);
        sound_sect_soul_stone_armor = BUILDER.comment("律灵学派魂石随从减伤").defineInRange("sound_sect_soul_stone_armor",0.5,0F,2147483647);
        sound_sect_soul_stone_owner_damage = BUILDER.comment("律灵学派魂石自身增伤").defineInRange("sound_sect_soul_stone_owner_damage",0.05,0F,2147483647);
        sound_sect_soul_stone_damage = BUILDER.comment("律灵学派魂石随从增伤").defineInRange("sound_sect_soul_stone_damage",0.25,0F,2147483647);
        sound_sect_soul_stone_power = BUILDER.comment("律灵学派魂石法强").defineInRange("sound_sect_soul_stone_power",0.1,0F,2147483647);
        aqua_sect_soul_stone_power = BUILDER.comment("源流学派魂石法强").defineInRange("aqua_sect_soul_stone_power",0.1,0F,2147483647);
        aqua_sect_soul_stone_time = BUILDER.comment("源流学派魂石buff时间").defineInRange("aqua_sect_soul_stone_time",5,0F,2147483647);
        aqua_sect_soul_stone_chance = BUILDER.comment("源流学派魂石buff提升概率").defineInRange("aqua_sect_soul_stone_chance",0.3,0F,2147483647);
        aqua_sect_soul_stone_level = BUILDER.comment("源流学派魂石最高buff提升等级").defineInRange("aqua_sect_soul_stone_level",10,0F,2147483647);
        eldritch_sect_soul_stone_damage = BUILDER.comment("邪术学派魂石伤害增幅").defineInRange("eldritch_sect_soul_stone_damage",0.075,0F,2147483647);
        eldritch_sect_soul_stone_time = BUILDER.comment("邪术学派魂石抑影时间").defineInRange("eldritch_sect_soul_stone_time",10,0F,2147483647);
        eldritch_sect_soul_stone_power = BUILDER.comment("邪术学派魂石法强").defineInRange("eldritch_sect_soul_stone_power",0.1,0F,2147483647);
        ender_sect_soul_stone_damage = BUILDER.comment("末影学派魂石伤害增幅").defineInRange("ender_sect_soul_stone_damage",0.1,0F,2147483647);
        ender_sect_soul_stone_time = BUILDER.comment("末影学派魂石抑影时间").defineInRange("ender_sect_soul_stone_time",10,0F,2147483647);
        ender_sect_soul_stone_power = BUILDER.comment("末影学派魂石法强").defineInRange("ender_sect_soul_stone_power",0.1,0F,2147483647);
        blood_sect_soul_stone_owner = BUILDER.comment("血腥学派魂石宠物吸血转化").defineInRange("blood_sect_soul_stone_owner",0.5,0F,2147483647);
        blood_sect_soul_stone_heal = BUILDER.comment("血腥学派魂石自身吸血").defineInRange("blood_sect_soul_stone_heal",0.15,0F,2147483647);
        blood_sect_soul_stone_power = BUILDER.comment("血腥学派魂石法强").defineInRange("blood_sect_soul_stone_power",0.1,0F,2147483647);
        nature_sect_soul_stone_power = BUILDER.comment("自然学派魂石法强").defineInRange("nature_sect_soul_stone_power",0.1,0F,2147483647);
        nature_sect_soul_stone_time = BUILDER.comment("自然学派魂石buff增加时间").defineInRange("nature_sect_soul_stone_time",0.2,0F,2147483647);
        nature_sect_soul_stone_chance = BUILDER.comment("自然学派魂石buff提升概率").defineInRange("nature_sect_soul_stone_chance",0.3,0F,2147483647);
        nature_sect_soul_stone_level = BUILDER.comment("自然学派魂石最高buff提升等级").defineInRange("nature_sect_soul_stone_level",15,0F,2147483647);
        evocation_sect_soul_stone_armor = BUILDER.comment("唤魔学派魂石随从减伤").defineInRange("evocation_sect_soul_stone_armor",0.3,0F,2147483647);
        evocation_sect_soul_stone_owner_damage = BUILDER.comment("唤魔学派魂石自身增伤").defineInRange("evocation_sect_soul_stone_owner_damage",0.05,0F,2147483647);
        evocation_sect_soul_stone_damage = BUILDER.comment("唤魔学派魂石随从增伤").defineInRange("evocation_sect_soul_stone_damage",0.15,0F,2147483647);
        evocation_sect_soul_stone_power = BUILDER.comment("唤魔学派魂石法强").defineInRange("evocation_sect_soul_stone_power",0.1,0F,2147483647);
        holy_sect_soul_stone_time = BUILDER.comment("神圣学派魂石时长").defineInRange("holy_sect_soul_stone_time",10,0F,2147483647);
        holy_sect_soul_stone_damage = BUILDER.comment("神圣学派魂石伤害增幅").defineInRange("holy_sect_soul_stone_damage",0.1,0F,2147483647);
        holy_sect_soul_stone_power = BUILDER.comment("神圣学派魂石法强").defineInRange("holy_sect_soul_stone_power",0.1,0F,2147483647);
        lightning_sect_soul_stone_time = BUILDER.comment("雷霆学派魂石最长超负荷时长").defineInRange("lightning_sect_soul_stone_time",10,0F,2147483647);
        lightning_sect_soul_stone_damage = BUILDER.comment("雷霆学派魂石伤害转化比例").defineInRange("lightning_sect_soul_stone_damage",0.4,0F,2147483647);
        lightning_sect_soul_stone_power = BUILDER.comment("雷霆学派魂石雷霆法强").defineInRange("lightning_sect_soul_stone_power",0.1,0F,2147483647);
        ice_sect_soul_stone_ice_power = BUILDER.comment("冰霜学派魂石冰霜法强").defineInRange("ice_sect_soul_stone_ice_power",0.1,0F,2147483647);
        ice_sect_soul_stone_time = BUILDER.comment("冰霜学派魂石冰封时间").defineInRange("ice_sect_soul_stone_time",10,0F,2147483647);
        ice_sect_soul_stone_ice_damage = BUILDER.comment("冰霜学派魂石冰封增伤").defineInRange("ice_sect_soul_stone_ice_damage",0.1,0F,2147483647);
        fire_sect_soul_stone_fire_max_damage = BUILDER.comment("炽焰学派魂石炽焰最大增幅").defineInRange("fire_sect_soul_stone_fire_max_damage",0.15,0F,2147483647);
        fire_sect_soul_stone_fire_min_damage = BUILDER.comment("炽焰学派魂石炽焰最小增幅").defineInRange("fire_sect_soul_stone_fire_min_damage",0.05,0F,2147483647);
        fire_sect_soul_stone_fire_power = BUILDER.comment("炽焰学派魂石炽焰法强").defineInRange("fire_sect_soul_stone_fire_power",0.1,0F,2147483647);
        wing_soul_stone = BUILDER.comment("飞翼魂石飞行速度").defineInRange("wing_soul_stone",1,0F,2147483647);
        aquatic_soul_stone = BUILDER.comment("水生魂石水下增伤").defineInRange("aquatic_soul_stone",0.15,0F,2147483647);
        animal_soul_stone = BUILDER.comment("动物魂石额外战利品数量").defineInRange("animal_soul_stone",1,0F,2147483647);
        arthropod_soul_stone = BUILDER.comment("节肢增伤").defineInRange("arthropod_soul_stone",0.15,0F,2147483647);
        death_soul_stone = BUILDER.comment("亡灵增伤").defineInRange("death_soul_stone",0.15,0F,2147483647);
        blaze_soul_stone = BUILDER.comment("狱灵增伤").defineInRange("blaze_soul_stone",0.15,0F,2147483647);
        forest_soul_stone = BUILDER.comment("森林间隔").defineInRange("forest_soul_stone",3,0F,2147483647);
        lush_soul_stone_saturation = BUILDER.comment("自然饱和度").defineInRange("lush_soul_stone_saturation",1,0F,2147483647);
        lush_soul_stone_food = BUILDER.comment("自然饥饿度").defineInRange("lush_soul_stone_food",1,0F,2147483647);
        ocean_soul_stone = BUILDER.comment("海洋游泳速度").defineInRange("ocean_soul_stone",0.50,0F,2147483647);
        ender_soul_stone_attack = BUILDER.comment("末地-末影人特攻").defineInRange("ender_soul_stone_attack",0.5,0F,2147483647);
        ender_soul_stone_armor = BUILDER.comment("末地-末影人特防").defineInRange("ender_soul_stone_armor",0.4,0F,2147483647);
        mushroom_soul_stone = BUILDER.comment("蘑菇魂石概率").defineInRange("mushroom_soul_stone",0.5,0F,2147483647);
        nether_soul_stone = BUILDER.comment("下界魂石增伤").defineInRange("nether_soul_stone",0.15,0F,2147483647);
        netherite_soul_stone = BUILDER.comment("下界合金魂石击退抗性").defineInRange("netherite_soul_stone",0.4,0F,2147483647);
        netherite_soul_stone_armor = BUILDER.comment("下界合金魂石护甲韧性").defineInRange("netherite_soul_stone_armor",3,0F,2147483647);
        coal_soul_stone = BUILDER.comment("煤炭魂石移速").defineInRange("coal_soul_stone",0.2,0F,2147483647);
        copper_soul_stone = BUILDER.comment("铜魂石挖掘速度").defineInRange("copper_soul_stone",0.5,0F,2147483647);
        emerald_soul_stone = BUILDER.comment("绿宝石魂石声望").defineInRange("emerald_soul_stone",100,0F,2147483647);
        redstone_soul_stone = BUILDER.comment("红石攻击速度").defineInRange("redstone_soul_stone",0.25,0F,2147483647);
        iron_soul_stone = BUILDER.comment("铁魂石护甲值").defineInRange("iron_soul_stone",5,0F,2147483647);
        gold_soul_stone = BUILDER.comment("金魂石附魔等级").defineInRange("gold_soul_stone",5,0F,2147483647);
        diamond_soul_stone_looting = BUILDER.comment("钻石魂石抢夺").defineInRange("diamond_soul_stone_looting",2,0F,100);
        diamond_soul_stone_fortune = BUILDER.comment("钻石魂石时运").defineInRange("diamond_soul_stone_fortune",2,0F,100);
        lapis_lazuli_soul_stone = BUILDER.comment("青金石经验倍率").defineInRange("lapis_lazuli_soul_stone",1,0F,100);
        BUILDER.pop();
        SPEC = BUILDER.build();
    }
}
